import sys
import os
from zero_shot_openai.llm.llm_linker import llm_generate_sql

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

question = "Quali sono le ragioni sociali, con i relativi codici fiscali, associate al tipo soggetto 'CLI' in una commessa?"

print("Sending question to GPT-4o mini...\n")
sql_lines = llm_generate_sql(question)

print("SQL generated by the LLM:\n")
print("\n".join(sql_lines))
